title: My Blog
author: Mary Farag
email: maryhfarag@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I’m glad you are here. My name is Mary Farag, a junior at East Brunswick High School. I have a strong interest in computer science, I love coding robots, and learning new programming languages!

# social links
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username: mfarag2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
